
function mygui ()
  MainFrm = figure ( ...
    'position', [200, 50, 750, 600],...
    'color',    [0.9, 0.9, 0.9]); 

  ImgFrmn = axes ( ...
    'position', [0.01, 0.585, 0.35, 0.4], ... 
    'xtick',    [], ... 
    'ytick',    [], ...
    'xlim',     [0, 1], ... 
    'ylim',     [0, 1]);
  
  ButtonFrm = uicontrol (MainFrm, ...
    'style',    'pushbutton', ... 
    'string',   'Select Image', ...
    'units',    'normalized', ...
    'position', [0.365, 0.76, 0.12, 0.05], ...
    'callback', { @previewImage, ImgFrmn});
 
  acop_check = uicontrol (MainFrm, ...
    "style", "checkbox", ...
    "units", "normalized", ...
    "string", " Invert?", ...
    "value", 0, ...
    "callback", { @updateinvers,ImgFrmn}, ...
    "position", [0.3655 0.67 0.12 0.09]);
  
  
  ImgFrmf = axes ( ...
    'position', [0.492, 0.585, 0.35, 0.4], ... 
    'xtick',    [], ... 
    'ytick',    [], ...
    'xlim',     [0, 1], ... 
    'ylim',     [0, 1]);
  
  q_slider = uicontrol (MainFrm,...
    "style", "slider",...
    "units", "normalized",...
    "string", "slider",...
    "value", 1,
    "position", [0.492 0.555 0.35 0.03]);
    
  ButtonFrmf = uicontrol (MainFrm, ...
    'style',    'pushbutton', ... 
    'string',   'Filter', ...
    'units',    'normalized', ...
    'position', [0.845, 0.76, 0.12, 0.05], ...
    'callback', { @FilterImage, ImgFrmf,q_slider});
    
  Title = text (0.95, -0.13, 'High', 'fontsize', 12);
  Title = text (-0.05, -0.13, 'Low', 'fontsize', 12);
  Title = text (-0.05+0.5, -0.13*1.5, 'Quality', 'fontsize', 12);
end

%% callback subfunction (in same file)
function previewImage (hObject, eventdata, ImageFrame)
  global  Img;
  global mg;
  [fname, fpath] = uigetfile();
  Img = imread (fullfile(fpath, fname));
  Img = adapt (Img);
  axes(ImageFrame);
  imshow(Img, []);
  axis image off
  mg=Img;
  

end

function updateinvers (hObject, eventdata,ImageFrame)
  global Img;
  global mg;
  axes(ImageFrame);
  mg=255-mg;
  imshow(mg, []);
  axis image off 
end

function FilterImage (hObject, eventdata, ImageFrame,sl)
  global Img;
  global FImg;
  v = get (sl, "value");
  v=(v*9.9)+0.1;
  v=10-v;
  ang = [0:v:180];
  FImg = Rampfl (Img,ang);
  axes(ImageFrame);
  imshow(FImg, []);
  axis image off 
  

end